name: Snyk Security Gate
on:
  pull_request: 
    branches:
      PROD
jobs:
  oss-security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check for high severity OSS vulnerabilites 
      uses: snyk/actions/node@master
      env: 
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with: 
        args: --severity-threshold=high --fail-on=upgradable
    
